version: '3'

volumes:
  postgres_data:

services:
  app:
    container_name: leave_app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    image: leave-app
    ports:
      - "3000:3000"
    command: rails s
    environment:
       - RAILS_SERVE_STATIC_FILES=true
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
